<?php
// Instrucciones, valores de los registros y memoria luego de ejecutar cada instrucción, descripcion de cada instruccion,
// descripcion de cada operacion y flag de cambio de estado de cada registro.
$instructions = array(
    "0" => array(
        "opDescription" => "Se carga el registro CX con el número 566E",
        "steps" => array(
            "0" => array(
                "ip" => array("data" => "0100"),
                "ri" => array("data" => "0000"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "0000"),
                "rdi" => array("data" => "0000"),
                "rda" => array("data" => "0000"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Estado previo a la ejecución"),
            ),
            "1" => array(
                "ip" => array("data" => "0100"),
                "ri" => array("data" => "0000"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "0000"),
                "rdi" => array("data" => "0100", "changed" => TRUE),
                "rda" => array("data" => "0000"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "El puntero de instrucción IP envía la dirección 0100 al registro de instrucción RDI"),
            ),
            "2" => array(
                "ip" => array("data" => "0100"),
                "ri" => array("data" => "B96E56", "changed" => TRUE),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "0000"),
                "rdi" => array("data" => "0100"),
                "rda" => array("data" => "B96E56", "changed" => TRUE),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La memoria principal envía los bytes de la instrucción que comienza en la posición 0100 al registro de datos RDA y de ahí los envía al registro de instrucción RI"),
            ),
            "3" => array(
                "ip" => array("data" => "0100"),
                "ri" => array("data" => "B96E56"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "0000"),
                "rdi" => array("data" => "0100"),
                "rda" => array("data" => "B96E56"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La unidad de control (UC) decodifica la instrucción -> Asignar 566E a CX"),
            ),
            "4" => array(
                "ip" => array("data" => "0100"),
                "ri" => array("data" => "B96E56"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E", "changed" => TRUE),
                "rdi" => array("data" => "0100"),
                "rda" => array("data" => "B96E56"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se copia el valor 566E (ya ubicado en el registro de datos RDA) al registro CX"),
            ),
            "5" => array(
                "ip" => array("data" => "0103", "changed" => TRUE),
                "ri" => array("data" => "B96E56"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0100"),
                "rda" => array("data" => "B96E56"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se incrementa el valor del puntero de instrucción IP con la longitud de la instrucción ejecutada (3 bytes)"),
            )
        )
    ),
    "1" => array(
        "opDescription" => "Se carga en la posición 1000 de memoria el contenido de CX",
        "steps" => array(
            "0" => array(
                "ip" => array("data" => "0103"),
                "ri" => array("data" => "B96E56"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0100"),
                "rda" => array("data" => "B96E56"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Estado previo a la ejecución"),
            ),
            "1" => array(
                "ip" => array("data" => "0103"),
                "ri" => array("data" => "B96E56"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0103", "changed" => TRUE),
                "rda" => array("data" => "B96E56"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "El puntero de instrucción IP envía la dirección 0103 al registro de instrucción RDI"),
            ),
            "2" => array(
                "ip" => array("data" => "0103"),
                "ri" => array("data" => "B90E0010", "changed" => TRUE),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0103"),
                "rda" => array("data" => "B90E0010", "changed" => TRUE),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La memoria principal envía los bytes de la instrucción que comienza en la posición 0103 al registro de datos RDA y de ahí los envía al registro de instrucción RI"),
            ),
            "3" => array(
                "ip" => array("data" => "0103"),
                "ri" => array("data" => "B90E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0103"),
                "rda" => array("data" => "B90E0010"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La unidad de control (UC) decodifica la instrucción -> Cargar la pos. de memoria [1000] con el valor de CX"),
            ),
            "4" => array(
                "ip" => array("data" => "0103"),
                "ri" => array("data" => "B90E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "1000", "changed" => TRUE),
                "rda" => array("data" => "B90E0010"),
                "mem1000" => array("data" => "0000"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se carga el registro de instrucción RDI con la dirección de memoria [1000]"),
            ),
            "5" => array(
                "ip" => array("data" => "0103"),
                "ri" => array("data" => "B90E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "1000"),
                "rda" => array("data" => "566E", "changed" => TRUE),
                "mem1000" => array("data" => "566E", "changed" => TRUE),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se carga el contenido de CX en el registro de datos RDA y la memoria principal mueve el contenido del RDA a la direccion apuntada por el registro de direcciones RDI"),
            ),
            "6" => array(
                "ip" => array("data" => "0107", "changed" => TRUE),
                "ri" => array("data" => "B90E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "1000"),
                "rda" => array("data" => "566E"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se incrementa el valor del puntero de instrucción IP con la longitud de la instrucción ejecutada (4 bytes)"),
            ),
        )
    ),
    "2" => array(
        "opDescription" => "Se suman los contenidos del reg. CX y de la pos. de memoria 1000 y se lo asigna a CX",
        "steps" => array(
            "0" => array(
                "ip" => array("data" => "0107"),
                "ri" => array("data" => "B90E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "1000"),
                "rda" => array("data" => "566E"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Estado previo a la ejecución"),
            ),
            "1" => array(
                "ip" => array("data" => "0107"),
                "ri" => array("data" => "B90E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0107", "changed" => TRUE),
                "rda" => array("data" => "566E"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "El puntero de instrucción IP envía la dirección 0107 al registro de instrucción RDI"),
            ),
            "2" => array(
                "ip" => array("data" => "0107"),
                "ri" => array("data" => "030E0010", "changed" => TRUE),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0107"),
                "rda" => array("data" => "030E0010", "changed" => TRUE),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La memoria principal envía los bytes de la instrucción que comienza en la posición 0107 al registro de datos RDA y de ahí los envía al registro de instrucción RI"),
            ),
            "3" => array(
                "ip" => array("data" => "0107"),
                "ri" => array("data" => "030E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "0107"),
                "rda" => array("data" => "030E0010"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La unidad de control (UC) decodifica la instrucción -> Sumar el contenido de la pos. de memoria [1000] en el registro CX"),
            ),
            "4" => array(
                "ip" => array("data" => "0107"),
                "ri" => array("data" => "030E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "1000", "changed" => TRUE),
                "rda" => array("data" => "030E0010"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se carga el registro de instrucción RDI con la dirección de memoria [1000]"),
            ),
            "5" => array(
                "ip" => array("data" => "0107"),
                "ri" => array("data" => "030E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "566E"),
                "rdi" => array("data" => "1000"),
                "rda" => array("data" => "566E", "changed" => TRUE),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "MP mueve el contenido de [1000] a RDA"),
            ),
            "6" => array(
                "ip" => array("data" => "0107"),
                "ri" => array("data" => "030E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "ACDC", "changed" => TRUE),
                "rdi" => array("data" => "1000"),
                "rda" => array("data" => "566E"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se suma el operando del registro de datos RDA en el registro CX"),
            ),
            "7" => array(
                "ip" => array("data" => "010B", "changed" => TRUE),
                "ri" => array("data" => "030E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "ACDC"),
                "rdi" => array("data" => "1000"),
                "rda" => array("data" => "566E"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se incrementa el valor del puntero de instrucción IP con la longitud de la instrucción ejecutada (4 bytes)"),
            ),
        )
    ),
    "3" => array(
        "opDescription" => "Se carga el registro AX con el contenido de CX",
        "steps" => array(
            "0" => array(
                "ip" => array("data" => "010B"),
                "ri" => array("data" => "030E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "ACDC"),
                "rdi" => array("data" => "1000"),
                "rda" => array("data" => "566E"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Estado previo a la ejecución"),
            ),
            "1" => array(
                "ip" => array("data" => "010B"),
                "ri" => array("data" => "030E0010"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "ACDC"),
                "rdi" => array("data" => "010B", "changed" => TRUE),
                "rda" => array("data" => "566E"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "El puntero de instrucción IP envía la dirección 010B al registro de instrucción RDI"),
            ),
            "2" => array(
                "ip" => array("data" => "010B"),
                "ri" => array("data" => "89C8", "changed" => TRUE),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "ACDC"),
                "rdi" => array("data" => "010B"),
                "rda" => array("data" => "89C8", "changed" => TRUE),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La memoria principal envía los bytes de la instrucción que comienza en la posición 0107 al registro de datos RDA y de ahí los envía al registro de instrucción RI"),
            ),
            "3" => array(
                "ip" => array("data" => "010B"),
                "ri" => array("data" => "89C8"),
                "ax" => array("data" => "0000"),
                "cx" => array("data" => "ACDC"),
                "rdi" => array("data" => "010B"),
                "rda" => array("data" => "89C8"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "La unidad de control (UC) decodifica la instrucción -> Copiar el contenido del registro CX al registro AX"),
            ),
            "4" => array(
                "ip" => array("data" => "010B"),
                "ri" => array("data" => "89C8"),
                "ax" => array("data" => "ACDC", "changed" => TRUE),
                "cx" => array("data" => "ACDC"),
                "rdi" => array("data" => "010B"),
                "rda" => array("data" => "89C8"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se copia directamente el contenido del registro CX al registro AX"),
            ),
            "5" => array(
                "ip" => array("data" => "010D", "changed" => TRUE),
                "ri" => array("data" => "89C8"),
                "ax" => array("data" => "ACDC"),
                "cx" => array("data" => "ACDC"),
                "rdi" => array("data" => "010B"),
                "rda" => array("data" => "89C8"),
                "mem1000" => array("data" => "566E"),
                "mem1001" => array("data" => "0000"),
                "description" => array("data" => "Se incrementa el valor del puntero de instrucción IP con la longitud de la instrucción ejecutada (2 bytes)"),
            ),
        )
    )
);

$instNum = $_POST["number"];
echo json_encode($instructions[$instNum]);
?>